### ISSUE TITLE
Wrong RateLimitPolicy sample

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-console-plugin#148]
The RateLimitPolicy provided as example when creating a new policy is not valid.

<img width="1526" alt="Screenshot 2024-11-12 at 17 02 28" src="https://github.com/user-attachments/assets/3dbd16ce-215a-4e28-b326-bf744a0c192a">

<br/><br/>

A correct one equivalent to the above is:

```yaml
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: example-ratelimitpolicy
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: prod-web
  limits:
    toystore-api-per-username:
      rates:
        - limit: 100
          window: 1s
        - limit: 1000
          window: 1m
      counters:
        - expression: auth.identity.username
```
