### ISSUE TITLE
Improve the UX for setting custom weight selectors in the DNSPolicy create page

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/kuadrant-console-plugin#60]
When the routing strategy is changed from Simple to Load Balanced, the `loadBalancing.geo` and `loadBalancing.weighted` fields become required.
In the UI, when you change from Simple routing strategy to Load Balanced, it looks like:

<img width="559" alt="image" src="https://github.com/user-attachments/assets/79d8d23f-82c7-4266-bc63-93aa3dfc0d8b">

A custom weight selector is then needed, set on the `loadBalancing.weighted.custom` key.
When you click the 'Add Custom Weight Selector' button, new fields are shown like this:

<img width="732" alt="image" src="https://github.com/user-attachments/assets/72f5291a-eef6-4374-9ae0-47e0bbd0180b">

You need to add 1 or more matchLabels or matchExpressions. (at least 1 of either, but can mix and match).
When you click 'Add Match Label', it looks like this:

<img width="1358" alt="image" src="https://github.com/user-attachments/assets/4cb3fbc6-4264-483b-9894-57b78b3e58df">

You can modify it, remove it, or add more.
These end up looking like this in yaml:

```yaml
spec:
  loadBalancing:
    geo:
      defaultGeo: eu
    weighted:
      custom:
        - selector:
            matchLabels:
              key-1: value1
              key-2: value2
```

When you click 'Add Match Expression', it looks like this:

<img width="1377" alt="image" src="https://github.com/user-attachments/assets/643bfa05-4e77-46f3-bf95-eeaa05afbdbd">

You can modify the key, operator and value. You can also add more values. 
If you set the operator to 'Exists' or 'NotExists', the values are removed.
Here's what it might look like in yaml:

```yaml
spec:
  loadBalancing:
    geo:
      defaultGeo: eu
    weighted:
      custom:
        - selector:
            matchExpressions:
              - key: test
                operator: In
                values:
                  - val1
                  - val2
```

Things can get a little confusing as you add more match labels and match expressions. Here's with 2 of either:

<img width="1381" alt="image" src="https://github.com/user-attachments/assets/26217640-27c5-4f21-aac1-d367fd4d5df6">

Functionally, it allows you to build up what's possible in the CRD spec.
However, there's definitely improvements to the layout (like grouping with labelled boxes, and limiting the width of fields and boxes) that would make for a better overall UX in this complex part of the view.
